Repository JetBrains/koog, pull requests merged in 2025-08, with the labels that each got.

#496 KG-169. Add support for setting the OpenTelemetry SDK in koog
  agents/agents-features/agents-features-opentelemetry/README.md
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetryConfig.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetryTest.kt
Labels: documentation

#551 KG-172. Add all messages to the inference span for Open Telemetry
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/ToolMessageEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetry.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/span/GenAIAgentSpan.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/OpenTelemetryTestAPI.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/ToolMessageEventTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetryTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/mock/MockToolGetWeather.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/span/GenAIAgentSpanTest.kt
Labels: bug

#550 Extract content metadata into a separate method
  rag/rag-base/src/commonMain/kotlin/ai/koog/rag/base/files/FileMetadata.kt
  rag/rag-base/src/commonMain/kotlin/ai/koog/rag/base/files/FileSystemProvider.kt
  rag/rag-base/src/commonMain/kotlin/ai/koog/rag/base/files/FilteredFileSystemProvider.kt
  rag/rag-base/src/jvmMain/kotlin/ai/koog/rag/base/files/JVMFileSystemProvider.kt
  rag/rag-base/src/jvmTest/kotlin/ai/koog/rag/base/files/JVMFileSystemProviderTest.kt
  rag/vector-storage/src/commonTest/kotlin/ai/koog/rag/vector/FileDocumentEmbeddingStorageTest.kt
  rag/vector-storage/src/commonTest/kotlin/ai/koog/rag/vector/FileVectorStorageTest.kt
  rag/vector-storage/src/commonTest/kotlin/ai/koog/rag/vector/TextFileDocumentEmbeddingStorageTest.kt
  rag/vector-storage/src/commonTest/kotlin/ai/koog/rag/vector/mocks/MockDocumentProviders.kt
Labels: enhancement, refactoring, tests

#559 Integration tests stabilization
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/AIAgentIntegrationTest.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/SingleLLMPromptExecutorIntegrationTest.kt
Labels: tests

#547 Add tool arguments for gen_ai.choice and gen_ai.assistant.message events (#462)
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/AssistantMessageEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/ChoiceEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/EventBodyFields.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/SystemMessageEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/ToolMessageEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/UserMessageEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetry.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/AssistantMessageEventTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/ChoiceEventTest.kt
Labels: bug

#568 KG-175. Add input.value and output.value attributes for ExecuteToolSpan
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/attribute/SpanAttributes.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetry.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/span/ExecuteToolSpan.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetryTest.kt
Labels: bug

#597 KG-221 Add an edit button to the docs
  docs/mkdocs.yml
Labels: documentation

#600 Consolidate embedding model test cases into a single test structure
  embeddings/embeddings-llm/src/commonTest/kotlin/ai/koog/embeddings/local/LLMEmbedderTest.kt
  embeddings/embeddings-llm/src/commonTest/kotlin/ai/koog/embeddings/local/OllamaEmbedderTest.kt
  embeddings/embeddings-llm/src/commonTest/kotlin/ai/koog/embeddings/local/OpenAIEmbedderTest.kt
Labels: tests

#627 Fix failing heavy tests
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/AIAgentIntegrationTest.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/AnthropicSchemaValidationIntegrationTest.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/RetryUtils.kt
Labels: tests

#635 [docs] Update docs with proper Maven dependency example
  README.md
  docs/docs/index.md
Labels: documentation

#629 Fix OllamaAgentIntegrationTest and AIAgentIntegrationTest
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/AIAgentIntegrationTest.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/OllamaAgentIntegrationTest.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/annotations/RetryExtension.kt
Labels: tests

#653 Update the nr of expected events in debugger tests
  agents/agents-features/agents-features-debugger/src/jvmTest/kotlin/ai/koog/agents/features/debugger/feature/DebuggerTest.kt
Labels: tests

#658 [WIP] KG-290. Update OpenTelemetry feature documentation with Langfuse/Weave integrations
  docs/docs/opentelemetry-support.md
Labels: documentation

#637 JSON structured output tests
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/MultipleLLMPromptExecutorIntegrationTest.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/SingleLLMPromptExecutorIntegrationTest.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/TestUtils.kt
  prompt/prompt-structure/src/commonTest/kotlin/ai/koog/prompt/structure/json/JsonStructuredDataTest.kt
Labels: tests

#668 Exclude flaky profiles from the run and add retries
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/AIAgentIntegrationTest.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/AIAgentMultipleLLMIntegrationTest.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/MultipleLLMPromptExecutorIntegrationTest.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/SingleLLMPromptExecutorIntegrationTest.kt
Labels: tests

#659 OpenAI-alike models' tests
  .github/workflows/heavy-tests.yml
  TESTING.md
  agents/agents-test/src/commonMain/kotlin/ai/koog/agents/testing/client/CapturingLLMClient.kt
  build.gradle.kts
  integration-tests/env.template.properties
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/SingleLLMPromptExecutorIntegrationTest.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/Models.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/TestUtils.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-deepseek-client/build.gradle.kts
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-deepseek-client/src/jvmTest/kotlin/deepseek/DeepSeekLLMClientTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openrouter-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openrouter/OpenRouterModels.kt
  prompt/prompt-executor/prompt-executor-llms-all/src/jvmTest/kotlin/ai/koog/prompt/executor/llms/all/SimpleAzureOpenAiExecutorTest.kt
  prompt/prompt-executor/prompt-executor-llms/build.gradle.kts
  prompt/prompt-executor/prompt-executor-llms/src/commonTest/kotlin/ai/koog/prompt/executor/llms/MultiLLMPromptExecutorTest.kt
  prompt/prompt-executor/prompt-executor-llms/src/commonTest/kotlin/ai/koog/prompt/executor/llms/SingleLLMPromptExecutorTest.kt
Labels: refactoring, tests

#691 Introduce test-utils module and refactor serialization tests
  koog-agents/build.gradle.kts
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/build.gradle.kts
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/ai21/BedrockAI21JambaSerialization.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/ai21/JambaDataModel.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/ai21/BedrockAI21JambaSerializationTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/ai21/JambaDataModelsTest.kt
  settings.gradle.kts
  test-utils/build.gradle.kts
  test-utils/gradle.properties
  test-utils/src/commonMain/kotlin/ai/koog/test/utils/SerializationHelpers.kt
  test-utils/src/commonTest/kotlin/ai/koog/test/utils/SerializationHelpersTest.kt
Labels: tests

#639 Add tracing tests
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/integration/TraceStructureTestBase.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/integration/langfuse/LangfuseTraceStructureTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/integration/weave/WeaveTraceStructureTest.kt
Labels: tests

#697 Update Koog (0.4.1) and dependency versions in demo-android-app
  examples/demo-android-app/gradle/libs.versions.toml
  examples/demo-android-app/gradle/wrapper/gradle-wrapper.jar
  examples/demo-android-app/gradle/wrapper/gradle-wrapper.properties
  examples/demo-android-app/gradlew
  examples/demo-android-app/gradlew.bat
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies
