Repository JetBrains/koog, pull requests merged in 2025-09, with the labels that each got.

#698 Fix property binding issues to make Koog Spring Boot auto-configuration work and add tests
  gradle/libs.versions.toml
  koog-spring-boot-starter/build.gradle.kts
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/AnthropicKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/DeepSeekKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/GoogleKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/KoogAutoConfig.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/KoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/OllamaKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/OpenAIKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/OpenRouterKoogProperties.kt
  koog-spring-boot-starter/src/test/kotlin/ai/koog/spring/KoogAutoConfigurationTest.kt
Labels: tests, bugfix

#715 KG-312 Add Java-compatible prompt executor (non-streaming)
  gradle/libs.versions.toml
  prompt/prompt-executor/prompt-executor-llms/build.gradle.kts
  prompt/prompt-executor/prompt-executor-llms/src/commonTest/kotlin/ai/koog/prompt/executor/llms/MockOpenAILLMClient.kt
  prompt/prompt-executor/prompt-executor-llms/src/commonTest/kotlin/ai/koog/prompt/executor/llms/MultiLLMPromptExecutorTest.kt
  prompt/prompt-executor/prompt-executor-llms/src/jvmMain/kotlin/ai/koog/prompt/executor/llms/Executors.kt
  prompt/prompt-executor/prompt-executor-llms/src/jvmTest/java/ai/koog/prompt/executor/llms/ExecutorsTest.java
  prompt/prompt-executor/prompt-executor-model/build.gradle.kts
  prompt/prompt-executor/prompt-executor-model/src/jvmMain/kotlin/ai/koog/prompt/executor/model/JavaPromptExecutor.kt
  prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/dsl/Prompt.kt
  prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/message/Message.kt
  test-utils/build.gradle.kts
Labels: enhancement, tests

#741 KG-162. Add tokens usage information for inference span in OTel
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/attribute/SpanAttributes.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetry.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/integration/Utils.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/integration/weave/WeaveSpanAdapter.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/span/GenAIAgentSpan.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/span/InferenceSpan.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/OpenTelemetryTestAPI.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetryTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/integration/TraceStructureTestBase.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/integration/UtilsTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/integration/langfuse/LangfuseTraceStructureTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/integration/weave/WeaveTraceStructureTest.kt
Labels: enhancement

#792 Update build prerequisites (CONTRIBUTING.md)
  CONTRIBUTING.md
Labels: documentation

#800 Divide integration tests in parallel
  .github/workflows/heavy-tests.yml
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/executor/SingleLLMPromptExecutorIntegrationTest.kt
  integration-tests/src/jvmTest/resources/media/test.wav
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openrouter-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openrouter/models/OpenRouterChatCompletion.kt
Labels: tests

#811 Add job names to heavy-tests workflow
  .github/workflows/heavy-tests.yml
Labels: tests

#823 Add GitHub Actions build status badges to README.md for visibility
  README.md
Labels: documentation

#779 Add iOS target for demo-compose-app
  .github/workflows/checks.yml
  .github/workflows/demo-compose-app.yml
  examples/demo-compose-app/README.md
  examples/demo-compose-app/app/build.gradle.kts
  examples/demo-compose-app/app/src/commonMain/kotlin/com/jetbrains/example/kotlin_agents_demo_app/agents/calculator/CalculatorTools.kt
  examples/demo-compose-app/app/src/iosMain/kotlin/Main.kt
  examples/demo-compose-app/app/src/iosMain/kotlin/com/jetbrains/example/kotlin_agents_demo_app/KoinApp.ios.kt
  examples/demo-compose-app/app/src/iosMain/kotlin/com/jetbrains/example/kotlin_agents_demo_app/settings/DataStoreAppSettings.kt
  examples/demo-compose-app/app/src/iosMain/kotlin/com/jetbrains/example/kotlin_agents_demo_app/settings/PrefPathProvider.kt
  examples/demo-compose-app/app/src/iosMain/kotlin/com/jetbrains/example/kotlin_agents_demo_app/theme/Theme.ios.kt
  examples/demo-compose-app/gradle/libs.versions.toml
  examples/demo-compose-app/iosApp/iosApp.xcodeproj/project.pbxproj
  examples/demo-compose-app/iosApp/iosApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  examples/demo-compose-app/iosApp/iosApp.xcodeproj/xcuserdata/se.xcuserdatad/xcschemes/iosApp.xcscheme
  examples/demo-compose-app/iosApp/iosApp.xcodeproj/xcuserdata/se.xcuserdatad/xcschemes/xcschememanagement.plist
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AccentColor.colorset/Contents.json
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon-20@2x.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon-20@2x~ipad.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon-20@3x.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon-20~ipad.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon-29.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon-29@2x.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon-29@2x~ipad.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon-29@3x.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon-29~ipad.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon-40@2x.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon-40@2x~ipad.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon-40@3x.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon-40~ipad.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon-60@2x~car.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon-60@3x~car.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon-83.5@2x~ipad.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon@2x.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon@2x~ipad.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon@3x.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon~ios-marketing.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon~ipad.png
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  examples/demo-compose-app/iosApp/iosApp/Assets.xcassets/Contents.json
  examples/demo-compose-app/iosApp/iosApp/Info.plist
  examples/demo-compose-app/iosApp/iosApp/Preview Content/Preview Assets.xcassets/Contents.json
  examples/demo-compose-app/iosApp/iosApp/iosApp.swift
  examples/demo-compose-app/settings.gradle.kts
Labels: enhancement

#835 Update mcp version to 0.7.2 with fix for android
  gradle/libs.versions.toml
Labels: dependencies

#855 Revive and parallelize integration tests
  .github/workflows/heavy-tests.yml
  agents/agents-test/src/commonMain/kotlin/ai/koog/agents/testing/tools/DummyAIAgentContext.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/agent/AIAgentIntegrationTest.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/agent/AIAgentMultipleLLMIntegrationTest.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/RetryUtils.kt
  integration-tests/src/jvmTest/resources/simplelogger.properties
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-google-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/google/DataModel.kt
Labels: tests

#863 KG-428 Document setVerbose(true) for message visibility in Langfuse
  docs/docs/opentelemetry-langfuse-exporter.md
  docs/docs/opentelemetry-support.md
  docs/docs/opentelemetry-weave-exporter.md
Labels: documentation

#836 add `additionalProperties` across clients
  agents/agents-features/agents-features-snapshot/build.gradle.kts
  agents/agents-features/agents-features-snapshot/src/jvmTest/kotlin/PersistencyRunsTwiceTest.kt
  agents/agents-features/agents-features-snapshot/src/jvmTest/kotlin/PersistencyTestUtils.kt
  agents/agents-features/agents-features-snapshot/src/jvmTest/resources/junit-platform.properties
  buildSrc/src/main/kotlin/ai/koog/gradle/plugins/CheckSplitPackagesPlugin.kt
  gradle/libs.versions.toml
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-anthropic-client/build.gradle.kts
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-anthropic-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/anthropic/AnthropicLLMClient.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-anthropic-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/anthropic/DataModel.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-anthropic-client/src/commonTest/kotlin/ai/koog/prompt/executor/clients/anthropic/AnthropicSerializationTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-deepseek-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/deepseek/DeepSeekLLMClient.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-deepseek-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/deepseek/DeepSeekParams.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-deepseek-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/deepseek/models/DeepSeekChatCompletion.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-deepseek-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/deepseek/DeepSeekParamsTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-deepseek-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/deepseek/models/DeepSeekSerializationTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-google-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/google/DataModel.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-google-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/google/GoogleLLMClient.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-google-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/google/GoogleSerializationTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/OllamaClient.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/dto/OllamaModels.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonTest/kotlin/ai/koog/prompt/executor/ollama/client/dto/OllamaSerializationTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAILLMClient.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAIParams.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/models/OpenAIChatCompletion.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/models/OpenAIResponsesAPI.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/openai/OpenAIChatParamsTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/openai/OpenAIResponsesParamsTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/openai/models/OpenAIChatCompletionRequestSerializationTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/openai/models/OpenAIResponsesAPIRequestSerializationTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openrouter-client/build.gradle.kts
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openrouter-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openrouter/OpenRouterLLMClient.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openrouter-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openrouter/OpenRouterParams.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openrouter-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openrouter/models/OpenRouterChatCompletion.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openrouter-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/openrouter/OpenRouterParamsValidationTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openrouter-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/openrouter/models/OpenRouterSerializationTest.kt
  prompt/prompt-executor/prompt-executor-clients/src/commonMain/kotlin/ai/koog/prompt/executor/clients/serialization/AdditionalPropertiesFlatteningSerializer.kt
  prompt/prompt-model/build.gradle.kts
  prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/params/LLMParams.kt
  prompt/prompt-model/src/jvmTest/kotlin/ai/koog/prompt/params/LLMParamsTest.kt
  test-utils/build.gradle.kts
  test-utils/src/commonMain/kotlin/ai/koog/test/utils/SerializationHelpers.kt
Labels: enhancement, tests

#886 Refactor spring boot starters
  docs/docs/spring-boot.md
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/AnthropicKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/DeepSeekKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/GoogleKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/KoogAutoConfig.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/OllamaKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/OpenAIKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/OpenRouterKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/RetryConfigKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/prompt/executor/clients/KoogLlmClientProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/prompt/executor/clients/RetryConfigKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/prompt/executor/clients/anthropic/AnthropicKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/prompt/executor/clients/anthropic/AnthropicLLMAutoConfiguration.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/prompt/executor/clients/deepseek/DeepSeekKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/prompt/executor/clients/deepseek/DeepSeekLLMAutoConfiguration.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/prompt/executor/clients/google/GoogleKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/prompt/executor/clients/google/GoogleLLMAutoConfiguration.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/prompt/executor/clients/ollama/OllamaKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/prompt/executor/clients/ollama/OllamaLLMAutoConfiguration.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/prompt/executor/clients/openai/OpenAIKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/prompt/executor/clients/openai/OpenAILLMAutoConfiguration.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/prompt/executor/clients/openrouter/OpenRouterKoogProperties.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/prompt/executor/clients/openrouter/OpenRouterLLMAutoConfiguration.kt
  koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/prompt/executor/clients/utils.kt
  koog-spring-boot-starter/src/main/resources/META-INF/config/koog/anthropic-llm.properties
  koog-spring-boot-starter/src/main/resources/META-INF/config/koog/deepseek-llm.properties
  koog-spring-boot-starter/src/main/resources/META-INF/config/koog/google-llm.properties
  koog-spring-boot-starter/src/main/resources/META-INF/config/koog/ollama-llm.properties
  koog-spring-boot-starter/src/main/resources/META-INF/config/koog/openai-llm.properties
  koog-spring-boot-starter/src/main/resources/META-INF/config/koog/openrouter-llm.properties
  koog-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  koog-spring-boot-starter/src/test/kotlin/ai/koog/spring/KoogAutoConfigurationTest.kt
  koog-spring-boot-starter/src/test/resources/junit-platform.properties
  utils/src/commonMain/kotlin/ai/koog/utils/lang/StringExtensions.kt
  utils/src/commonTest/kotlin/ai/koog/utils/lang/StringExtensionsTest.kt
Labels: documentation, enhancement, refactoring

#734 fix: Google: use maxTokens from params
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-google-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/google/GoogleLLMClient.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-google-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/google/GoogleLLMClientTest.kt
Labels: bugfix
