Repository JetBrains/koog, pull requests merged in 2025-07, with the labels that each got.

#386 Add integration test for LLM requests without tool usage
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/SimpleAgentIntegrationTest.kt
Labels: tests

#385 Add integration tests for parallel tool execution in AIAgent.
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/AIAgentIntegrationTest.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/TestUtils.kt
  prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/message/Message.kt
Labels: tests

#391 Add tests for tool execution of tools with complex parameters.
  agents/agents-tools/src/commonTest/kotlin/ai/koog/agents/core/tools/serialization/ToolComplexParameterTypesTest.kt
Labels: tests

#405 Add RetryExtension and OllamaTestFixtureExtension to OllamaAgentIntegrationTest
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/OllamaAgentIntegrationTest.kt
Labels: tests

#401 JBAI-14524. Fix Open Telemetry attributes conversion logic
  agents/agents-features/agents-features-opentelemetry/README.md
  agents/agents-features/agents-features-opentelemetry/build.gradle.kts
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/attribute/EventAttributes.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/attribute/SpanAttributes.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/attribute/attributes.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/AssistantMessageEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/ChoiceEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/EventBodyField.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/EventBodyFields.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/GenAIAgentEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/SystemMessageEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/ToolMessageEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/UserMessageEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetry.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetryConfig.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/feature/span/AgentRunSpan.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/span/ExecuteToolSpan.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/span/GenAIAgentSpan.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/span/InferenceSpan.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/span/InvokeAgentSpan.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/span/SpanEndStatus.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/span/SpanProcessor.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/attribute/AttributeExtensionTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/EventBodyFieldTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/GenAIAgentEventTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetryTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/mock/MockEventBodyField.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/mock/MockGenAIAgentEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/mock/MockGenAIAgentSpan.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/mock/MockSpan.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/mock/MockSpanExporter.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/mock/MockTracer.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/mock/UnsupportedType.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/span/GenAIAgentSpanTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/span/SpanProcessorTest.kt
Labels: enhancement

#419 AWS Bedrock tests + serialization/deserialization tests for Bedrock providers
  .github/workflows/heavy-tests.yml
  build.gradle.kts
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/SingleLLMPromptExecutorIntegrationTest.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/Models.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/TestUtils.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/build.gradle.kts
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/BedrockToolSerializationTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/ai21/BedrockAI21JambaSerializationTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/ai21/JambaDataModelsTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/amazon/BedrockAmazonNovaSerializationTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/amazon/NovaDataModelsTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/anthropic/BedrockAnthropicClaudeSerializationTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/meta/BedrockMetaLlamaSerializationTest.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/meta/LlamaDataModelsTest.kt
Labels: tests

#423 JBAI-14524. Update dependencies for Open Telemetry module
  agents/agents-features/agents-features-opentelemetry/build.gradle.kts
  examples/src/main/kotlin/ai/koog/agents/example/features/opentelemetry/OpenTelemetry.kt
Labels: bug, enhancement

#435 Fix custom moderating model selection in graph and single-message moderation
  agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/context/AIAgentLLMContext.kt
  agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/extension/AIAgentNodes.kt
  examples/build.gradle.kts
  examples/src/main/kotlin/ai/koog/agents/example/moderation/JokesWithModeration.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/BedrockLLMClient.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/OllamaClient.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAILLMClient.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAIModerationInput.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAIModerationModels.kt
Labels: bug, enhancement

#441 KG-135. Fix verbose flag behavior for event body fields in Open Telemetry
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/AssistantMessageEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/ChoiceEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/GenAIAgentEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/ModerationResponseEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/SystemMessageEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/ToolMessageEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/UserMessageEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/span/GenAIAgentSpan.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/AssistantMessageEventTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/ChoiceEventTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/EventBodyFieldTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/ModerationResponseEventTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/SystemMessageEventTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/ToolMessageEventTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/UserMessageEventTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetryTest.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/mock/MockGenAIAgentEvent.kt
  agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/mock/MockLLMProvider.kt
  prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/dsl/ModerationAPI.kt
Labels: bug, documentation, enhancement

#465 Add link to KG tracker to readme & docs header
  CONTRIBUTING.md
  README.md
  docs/overrides/partials/header.html
Labels: documentation

#458 Cover ai.koog.agents.core.agent.context with tests
  agents/agents-core/build.gradle.kts
  agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/context/AIAgentContext.kt
  agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/context/AIAgentContextBase.kt
  agents/agents-core/src/commonTest/kotlin/ai/koog/agents/core/agent/context/AIAgentContextTest.kt
  agents/agents-core/src/commonTest/kotlin/ai/koog/agents/core/agent/context/AIAgentLLMContextTest.kt
  agents/agents-core/src/commonTest/kotlin/ai/koog/agents/core/agent/context/AgentTestBase.kt
  agents/agents-core/src/commonTest/kotlin/ai/koog/agents/core/agent/context/element/AgentRunInfoContextElementTest.kt
  agents/agents-core/src/commonTest/kotlin/ai/koog/agents/core/agent/context/element/NodeInfoContextElementTest.kt
  agents/agents-core/src/jvmTest/kotlin/ai/koog/agents/core/agent/context/AIAgentLLMContextConcurrencyTest.kt
Labels: tests

#492 KG-174. Fix failures for remote writer tests caused by timeout
  agents/agents-features/agents-features-common/src/jvmTest/kotlin/ai/koog/agents/features/remote/server/FeatureMessageRemoteServerTest.kt
  agents/agents-features/agents-features-common/src/jvmTest/kotlin/ai/koog/agents/features/writer/FeatureMessageRemoteWriterTest.kt
  agents/agents-features/agents-features-trace/src/jvmTest/kotlin/ai/koog/agents/features/tracing/writer/TraceFeatureMessageRemoteWriterTest.kt
Labels: tests

#490 KG-173. Move choice extensions from agents-core to agents-ext module
  agents/agents-ext/src/commonMain/kotlin/ai/koog/agents/ext/agent/AIAgentExt.kt
  agents/agents-ext/src/commonMain/kotlin/ai/koog/agents/ext/llm/choice/AIAgentNodesWithChoiceExt.kt
  agents/agents-ext/src/commonMain/kotlin/ai/koog/agents/ext/llm/choice/ChoiceSelectionStrategy.kt
  agents/agents-ext/src/commonMain/kotlin/ai/koog/agents/ext/llm/choice/PromptExecutorWithChoiceSelection.kt
  agents/agents-ext/src/commonTest/kotlin/ai/koog/agents/ext/llm/choice/ChoiceSelectionStrategyTest.kt
  examples/src/main/kotlin/ai/koog/agents/example/chess/choice/AskUserChoiceSelectionStrategy.kt
  examples/src/main/kotlin/ai/koog/agents/example/chess/choice/ChessChoiceExecutor.kt
  examples/src/main/kotlin/ai/koog/agents/example/chess/choice/ChessChoiceNodes.kt
  prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/build.gradle.kts
  prompt/prompt-executor/prompt-executor-model/build.gradle.kts
Labels: refactoring
