Repository JetBrains/koog, pull requests merged in 2025-10, with the labels that each got.

#889 Add integration tests for executing tools with primitive types combinations
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/executor/ToolDescriptorIntegrationTest.kt
Labels: tests

#904 Add `agentId` to all Persistence methods instead of `persistencyId`
  agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/context/AIAgentLLMContext.kt
  agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/feature/AIAgentPipeline.kt
  agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/feature/handler/strategy/StrategyEventContext.kt
  agents/agents-features/agents-features-snapshot/Module.md
  agents/agents-features/agents-features-snapshot/README.md
  agents/agents-features/agents-features-snapshot/src/commonMain/kotlin/ai/koog/agents/snapshot/feature/Persistency.kt
  agents/agents-features/agents-features-snapshot/src/commonMain/kotlin/ai/koog/agents/snapshot/providers/InMemoryPersistencyStorageProvider.kt
  agents/agents-features/agents-features-snapshot/src/commonMain/kotlin/ai/koog/agents/snapshot/providers/NoPersistencyStorageProvider.kt
  agents/agents-features/agents-features-snapshot/src/commonMain/kotlin/ai/koog/agents/snapshot/providers/PersistencyStorageProvider.kt
  agents/agents-features/agents-features-snapshot/src/commonMain/kotlin/ai/koog/agents/snapshot/providers/file/FilePersistencyStorageProvider.kt
  agents/agents-features/agents-features-snapshot/src/jvmMain/kotlin/ai/koog/agents/snapshot/providers/file/JVMFilePersistencyStorageProvider.kt
  agents/agents-features/agents-features-snapshot/src/jvmTest/kotlin/CheckpointsTests.kt
  agents/agents-features/agents-features-snapshot/src/jvmTest/kotlin/NodeUniquenessCheckpointTest.kt
  agents/agents-features/agents-features-snapshot/src/jvmTest/kotlin/PersistencyRestoreStrategyTests.kt
  agents/agents-features/agents-features-snapshot/src/jvmTest/kotlin/PersistencyRunsTwiceTest.kt
  agents/agents-features/agents-features-snapshot/src/jvmTest/kotlin/SimpleGraphCheckpointTest.kt
  agents/agents-features/agents-features-snapshot/src/jvmTest/kotlin/SubgraphCheckpointsTest.kt
  agents/agents-features/agents-features-snapshot/src/jvmTest/kotlin/SubgraphSetExecutionPointTest.kt
  agents/agents-features/agents-features-snapshot/src/jvmTest/kotlin/TestStrategies.kt
  agents/agents-features/agents-features-snapshot/src/jvmTest/kotlin/ai/koog/agents/snapshot/providers/file/FileAgentCheckpointStorageProviderTest.kt
  agents/agents-features/agents-features-snapshot/src/jvmTest/kotlin/ai/koog/agents/snapshot/providers/file/FileCheckpointsTests.kt
  agents/agents-features/agents-features-sql/src/commonMain/kotlin/ai/koog/agents/features/sql/providers/SQLPersistencyStorageProvider.kt
  agents/agents-features/agents-features-sql/src/jvmMain/kotlin/ai/koog/agents/features/sql/providers/ExposedPersistencyStorageProvider.kt
  agents/agents-features/agents-features-sql/src/jvmMain/kotlin/ai/koog/agents/features/sql/providers/H2PersistencyStorageProvider.kt
  agents/agents-features/agents-features-sql/src/jvmMain/kotlin/ai/koog/agents/features/sql/providers/MySQLPersistencyStorageProvider.kt
  agents/agents-features/agents-features-sql/src/jvmMain/kotlin/ai/koog/agents/features/sql/providers/PostgresPersistencyStorageProvider.kt
  agents/agents-features/agents-features-sql/src/jvmTest/kotlin/ai/koog/agents/features/sql/providers/H2PersistencyStorageProviderTest.kt
  agents/agents-features/agents-features-sql/src/jvmTest/kotlin/ai/koog/agents/features/sql/providers/MySQLPersistencyStorageProviderTest.kt
  agents/agents-features/agents-features-sql/src/jvmTest/kotlin/ai/koog/agents/features/sql/providers/PostgresPersistencyStorageProviderTest.kt
  agents/agents-features/agents-features-sql/src/jvmTest/kotlin/ai/koog/agents/features/sql/providers/SQLPersistenceProvidersTest.kt
  docs/docs/agent-persistence.md
  examples/simple-examples/gradle.properties
  examples/simple-examples/src/main/kotlin/ai/koog/agents/example/snapshot/CheckpointExample.kt
  examples/simple-examples/src/main/kotlin/ai/koog/agents/example/snapshot/FilePersistentAgentExample.kt
  examples/simple-examples/src/main/kotlin/ai/koog/agents/example/snapshot/SnapshotExample.kt
  examples/simple-examples/src/main/kotlin/ai/koog/agents/example/snapshot/sql/SQLPersistentAgentExample.kt
  integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/agent/AIAgentIntegrationTest.kt
Labels: refactoring

#905 #903 Add error handling in LocalFileMemoryProvider
  agents/agents-features/agents-features-memory/src/commonMain/kotlin/ai/koog/agents/memory/providers/LocalFileMemoryProvider.kt
  agents/agents-features/agents-features-memory/src/jvmTest/kotlin/ai/koog/agents/memory/providers/LocalFileMemoryProviderTest.kt
Labels: enhancement, bugfix

#933 KG-449. Fix flaky test that check default port for the Debugger agent feature
  agents/agents-features/agents-features-debugger/src/jvmTest/kotlin/ai/koog/agents/features/debugger/feature/DebuggerTest.kt
Labels: tests
